### ISSUE TITLE
Have you considered Google Cloud Pub/Sub as Event Stream/Queue/Bus?

### ISSUE THREAD

**Issue by shafqatevo** [Rotorsoft/firebase-event-store#1]
Hi,

This looks so exciting! We're also embarking on a CQRS-ES project with Firestore as backend and exploring our options. We'll only have Cloud Functions in the backend and AngularDart and Flutter for the client apps.

So, have you considered Google's Cloud Pub/Sub for event stream/queue/bus? I have seen it being used in conjunction with Firebase services including Firestore in one of Google's talks.

Also, do you see any major limitations of using Firestore as general purpose Event Store?

**Comment by shafqatevo** [comment]
Seems Firestore is not an ideal solution currently for server-side event handling mainly due to the 10 seconds delay:
https://firebase.google.com/docs/functions/firestore-events#limitations_and_guarantees

On the other hand, Cloud Pub/Sub doesn't guarantee ordering, which doesn't matter much unless there is transactional thresholds involved, in which case a Firestore "holding table" would be necessary:
https://cloud.google.com/pubsub/docs/ordering

**Comment by Rotorsoft** [comment]
Hi
I’ve been using Firestore just to prototype apps since it’s still in beta. Have not seen any performance issues  yet, the 10 seconds cold start is not a big deal. The good thing is that Firebase is practically free including https hosting, storage, cloud functions, and authentication services. I only have one “command” cloud function in my api and use Vue.js in my PWA apps. Firebase is missing a timer function and pub/sub service and I have considered Google’s but don’t need it yet so I’m waiting for ideally a Kafka like one.

**Comment by shafqatevo** [comment]
Thanks @Rotorsoft !

PubSub is their message queue, meant to be used with other Firebase services. It is somewhat workable as a Kafka replacement and better alternative as a message queue than using Firestore for that purpose.

**Comment by Rotorsoft** [comment]
The event store already covers the producer side of a Kafka like approach. All is needed to get a decent bus is a structurally and temporarily decoupled mechanism to push events to registered consumers and keep track of their confirmed reading offset in the log (also like Kafka but with the added benefit of simpler consumers just focused on business logic since the bus will push instead of the consumers polling and keeping track of their position). I will probably drop some code soon to test this approach.

**Comment by shafqatevo** [comment]
That sounds great! Meanwhile, I'll report back what final solution our team converges to. We've finalized use of PubSub but will require some mechanisms for event store persistence and maybe even state store for the Aggregate Roots in our DDD model.
